export const storageKey = {
  ACCESS_TOKEN: "ACCESS_TOKEN",
  REFRESH_TOKEN: "REFRESH_TOKEN",
  ID: "USER_ID",
  FIRST_NAME: "FIRST_NAME",
  LAST_NAME: "LAST_NAME",
  DOB: "DOB",
  USERNAME: "USERNAME",
  EMAIL: "EMAIL",
  PHONE: "PHONE",
  LANGUAGE: "LANGUAGE",
}
