export const locationTypesDatas = [
  { id: 1, en: "Indoors", vi: "Trong nhà" },
  { id: 2, en: "Outdoors", vi: "Ngoài trời" },
  { id: 3, en: "Food & beverages", vi: "Thức ăn & đồ uống" },
  { id: 4, en: "Transportation & Tours", vi: "Vận chuyển & Tour" },
]

export const indoors = [
  { id: 1, en: "Airport Lounges", vi: "Phòng Chờ Sân Bay" },
  { id: 2, en: "Ancient Ruins", vi: "Địa Danh Cổ Xưa" },
  { id: 3, en: "Antique Shops", vi: "Cửa Hàng Đồ Cổ" },
  { id: 4, en: "Aquariums", vi: "Thủy Cung" },
  { id: 5, en: "Architectural Buildings", vi: "Công Trình Kiến Trúc" },
  { id: 6, en: "Art Galleries", vi: "Phòng Trưng Bày Nghệ Thuật" },
  { id: 7, en: "Bars & Clubs", vi: "Quán Bar & Câu Lạc Bộ" },
  { id: 8, en: "Beach & Pool Clubs", vi: "Câu Lạc Bộ Bãi Biển & Hồ Bơi" },
  { id: 9, en: "Blues Bars", vi: "Quán Bar Blues" },
  { id: 10, en: "Cabarets", vi: "Rạp Hát Thể Loại Cabaret" },
  { id: 11, en: "Casinos", vi: "Sòng Bạc" },
  { id: 12, en: "Cigar Bars", vi: "Quán Hút Sigar" },
  { id: 13, en: "Churches & Cathedrals", vi: "Nhà Thờ & Nhà Thờ Chính Tòa" },
  { id: 14, en: "Climbing Tours", vi: "Tour Leo Núi" },
  { id: 15, en: "Coffee & Tea Tours", vi: "Tour và Nếm Cà Phê & Trà" },
  { id: 16, en: "Coffeehouses", vi: "Quán Cà Phê" },
  { id: 17, en: "Concerts", vi: "Buổi Hòa Nhạc" },
  { id: 18, en: "Cooking Classes", vi: "Lớp Học Nấu Ăn" },
  { id: 19, en: "Cultural Events", vi: "Sự Kiện Văn Hóa" },
  { id: 20, en: "Dinner Theaters", vi: "Nhà Hát Ăn Tối" },
  { id: 21, en: "Educational sites", vi: "Các Trang Thông Tin Giáo Dục" },
  { id: 22, en: "Escape Games", vi: "Trò Chơi Trốn Thoát" },
  { id: 23, en: "Factory Outlets", vi: "Cửa Hàng Nhà Máy" },
  { id: 24, en: "Factory Tours", vi: "Tour Nhà Máy" },
  { id: 25, en: "Farmers Markets", vi: "Chợ Nông Sản" },
  { id: 26, en: "Fashion Shows & Tours", vi: "Tour và Buổi Trình Diễn Thời Trang" },
  { id: 27, en: "Farms", vi: "Trang Trại" },
  { id: 28, en: "Flea & Street Markets", vi: "Chợ Trời & Chợ Đường Phố" },
  { id: 29, en: "Game & Entertainment Centers", vi: "Trung Tâm Trò Chơi & Giải Trí" },
  { id: 30, en: "Gardens", vi: "Khu Vườn" },
  { id: 31, en: "Gay Bars", vi: "Quán Bar Chủ Đề Gay" },
  { id: 32, en: "Government Buildings", vi: "Công Trình Chính Phủ" },
  { id: 33, en: "Health Clubs", vi: "Câu Lạc Bộ Sức Khỏe" },
  { id: 34, en: "Helicopter Tours", vi: "Tour Trực Thăng" },
  { id: 35, en: "Historic Sites", vi: "Di Tích Lịch Sử" },
  { id: 36, en: "Historic Walking Areas", vi: "Khu Vực Đi Bộ Lịch Sử" },
  { id: 37, en: "History Museums", vi: "Bảo Tàng Lịch Sử" },
  { id: 38, en: "Hot Springs & Geysers", vi: "Suối Nước Nóng & Núi Lửa Phun Trào" },
  { id: 39, en: "Hammams & Turkish Baths", vi: "Hammams & Bể Tắm Thổ Nhĩ Kỳ" },
  { id: 40, en: "Jazz Bars", vi: "Quán Bar Nhạc Jazz" },
  { id: 41, en: "Karaoke Bars", vi: "Quán Bar Karaoke" },
  { id: 42, en: "Libraries", vi: "Thư Viện" },
  { id: 43, en: "Lessons & Workshops", vi: "Các Bài Học & Các Phòng Thí Nghiệm" },
  { id: 44, en: "Lookouts", vi: "Điểm Quan Sát" },
  { id: 45, en: "Luaus", vi: "Lễ Hội Luaus" },
  { id: 46, en: "Military Bases & Facilities", vi: "Cơ Sở Quân Sự & Cơ Sở" },
  { id: 47, en: "Military Museums", vi: "Bảo Tàng Quân Sự" },
  { id: 48, en: "Movie Theaters", vi: "Rạp Chiếu Phim" },
  { id: 49, en: "Motorcycle Trails", vi: "Đường Mòn Mô Tô" },
  { id: 50, en: "Multi-day Tours", vi: "Tour Nhiều Ngày" },
  { id: 51, en: "Natural History Museums", vi: "Bảo Tàng Lịch Sử Tự Nhiên" },
  { id: 52, en: "Night Tours", vi: "Tour Buổi Tối" },
  { id: 53, en: "Observation Decks & Towers", vi: "Tháp Quan Sát & Tầng Hầm" },
  { id: 54, en: "Onsen Resorts", vi: "Khu Nghỉ Dưỡng Onsen" },
  { id: 55, en: "Operas", vi: "Nhà Hát Opera" },
  { id: 56, en: "Paint & Pottery Studios", vi: "Các Xưởng Sơn & Gốm Sứ" },
  { id: 57, en: "Photography Tours", vi: "Tour Nhiếp Ảnh" },
  { id: 58, en: "Playgrounds", vi: "Sân Chơi" },
  { id: 59, en: "Religious Sites", vi: "Các Di Tích Tôn Giáo" },
  { id: 60, en: "Segway Tours", vi: "Tour Xe Đạp Điện" },
  { id: 61, en: "Scenic Walking Areas", vi: "Khu Vực Đi Bộ Thơ Mộng" },
  { id: 62, en: "Scuba & Snorkelling", vi: "Lặn Biển & Lặn Ống" },
  { id: 63, en: "Shooting Ranges", vi: "Khu Vực Bắn Súng" },
  { id: 64, en: "Shopping Malls", vi: "Trung Tâm Thương Mại" },
  { id: 65, en: "Shopping Tours", vi: "Tour Mua Sắm" },
  { id: 66, en: "Sightseeing Tours", vi: "Tour Tham Quan" },
  { id: 67, en: "Speciality & Gift Shops", vi: "Các Cửa Hàng Đặc Sản & Quà Tặng" },
  { id: 68, en: "Speciality Museums", vi: "Bảo Tàng Đặc Sản" },
  { id: 69, en: "Spas", vi: "Khu Nghỉ Dưỡng Spa" },
  { id: 70, en: "Theater & Performances", vi: "Nhà Hát & Biểu Diễn" },
  { id: 71, en: "Theaters", vi: "Rạp Hát" },
  { id: 72, en: "Thermal Spas", vi: "Khu Nghỉ Dưỡng Suối Nước Nóng" },
  { id: 73, en: "Visitor Centers", vi: "Trung Tâm Khách Hàng" },
  { id: 74, en: "Wine Bars", vi: "Quán Bar Rượu" },
]

export const outdoors = [
  { id: 75, en: "4WD, ATV & Off-Road Tours", vi: "Tour Xe Máy 4 Bánh, ATV & Off-Road" },
  { id: 76, en: "Adrenaline & Extreme Tours", vi: "Tour Mạo Hiểm & Cực Đoan" },
  { id: 77, en: "Arenas & Stadiums", vi: "Đấu Trường & Sân Vận Động" },
  { id: 78, en: "Beaches", vi: "Bãi Biển" },
  { id: 79, en: "Bike Tours", vi: "Tour Xe Đạp" },
  { id: 80, en: "Boat Rentals", vi: "Thuê Xe Đò" },
  { id: 81, en: "Boat Tours", vi: "Tour Bằng Thuyền" },
  { id: 82, en: "Caverns & Caves", vi: "Hang Động" },
  { id: 83, en: "Cemeteries", vi: "Nghĩa Trang" },
  { id: 84, en: "Churches & Cathedrals", vi: "Nhà Thờ & Nhà Thờ Chính Tòa" },
  { id: 85, en: "Day Trips", vi: "Chuyến Đi Trong Ngày" },
  { id: 86, en: "Deserts", vi: "Sa Mạc" },
  { id: 87, en: "Duck Tours", vi: "Tour Xe Thú" },
  { id: 88, en: "Ferries", vi: "Phà" },
  { id: 89, en: "Fishing Charters & Tours", vi: "Tour Câu Cá & Du Thuyền" },
  { id: 90, en: "Golf Courses", vi: "Sân Golf" },
  { id: 91, en: "Hiking & Camping Tours", vi: "Tour Leo Núi & Cắm Trại" },
  { id: 92, en: "Hiking Trails", vi: "Đường Mòn Đi Bộ" },
  { id: 93, en: "Historic Walking Areas", vi: "Khu Vực Đi Bộ Lịch Sử" },
  { id: 94, en: "Hop-On Hop-Off Tours", vi: "Tour Xe Buýt Đi Điểm Đến" },
  { id: 95, en: "Horseback Riding Tours", vi: "Tour Cưỡi Ngựa" },
  { id: 96, en: "Islands", vi: "Các Đảo" },
  { id: 97, en: "Kayaking & Canoeing", vi: "Đi Kayak & Đi Thuyền" },
  { id: 98, en: "Lighthouses", vi: "Hải Đăng" },
  { id: 99, en: "Lookouts", vi: "Điểm Quan Sát" },
  { id: 100, en: "Marinas", vi: "Bến Tàu" },
  { id: 101, en: "Miniature Golf", vi: "Golf Thu Nhỏ" },
  { id: 102, en: "Mountains", vi: "Núi" },
  { id: 103, en: "Mountains", vi: "Núi" },
  { id: 104, en: "Multi-day Tours", vi: "Tour Nhiều Ngày" },
  { id: 105, en: "National Parks", vi: "Công Viên Quốc Gia" },
  { id: 106, en: "Nature & Wildlife Areas", vi: "Khu Vực Thiên Nhiên & Động Vật Hoang Dã" },
  { id: 107, en: "Nature & Wildlife Areas", vi: "Khu Vực Thiên Nhiên & Động Vật Hoang Dã" },
  { id: 108, en: "Nature & Wildlife Areas", vi: "Khu Vực Thiên Nhiên & Động Vật Hoang Dã" },
  { id: 109, en: "Nature & Wildlife Tours", vi: "Tour Thiên Nhiên & Động Vật Hoang Dã" },
  { id: 110, en: "Neighborhoods", vi: "Khu Phố" },
  { id: 111, en: "Night Tours", vi: "Tour Buổi Tối" },
  { id: 112, en: "Parks", vi: "Công Viên" },
  { id: 113, en: "Piers & Boardwalks", vi: "Cầu Cảng & Đường Dạo Bộ" },
  { id: 114, en: "River Rafting & Tubing", vi: "Đi Rafting Trên Sông & Chèo Bè" },
  { id: 115, en: "Running Tours", vi: "Tour Chạy Bộ" },
  { id: 116, en: "Scenic Drives", vi: "Đường Dẫn Cảnh Đẹp" },
  { id: 117, en: "Scenic Drives", vi: "Đường Dẫn Cảnh Đẹp" },
  { id: 118, en: "Scenic Railroads", vi: "Đường Sắt Cảnh Quan" },
  { id: 119, en: "Scenic Railroads", vi: "Đường Sắt Cảnh Quan" },
  { id: 120, en: "Scenic Walking Areas", vi: "Khu Vực Đi Bộ Thơ Mộng" },
  { id: 121, en: "Scenic Walking Areas", vi: "Khu Vực Đi Bộ Thơ Mộng" },
  { id: 122, en: "Sightseeing Tours", vi: "Tour Tham Quan" },
  { id: 123, en: "Sporting Events", vi: "Sự Kiện Thể Thao" },
  { id: 124, en: "Stand Up Paddleboarding", vi: "Đi Stand Up Paddleboarding" },
  { id: 125, en: "State Parks", vi: "Công Viên Bang" },
  { id: 126, en: "Trams", vi: "Xe Điện" },
  { id: 127, en: "Valleys", vi: "Thung Lũng" },
  { id: 128, en: "Valleys", vi: "Thung Lũng" },
  { id: 129, en: "Water Parks", vi: "Công Viên Nước" },
  { id: 130, en: "Waterfalls", vi: "Thác Nước" },
  {
    id: 131,
    en: "Zipline & Aerial Adventure Parks",
    vi: "Công Viên Phi Hành & Phiêu Lưu Trên Cáp Treo",
  },
  { id: 132, en: "Zoos", vi: "Sở Thú" },
]

export const food_beverage = [
  { id: 133, en: "Beer Tastings & Tours", vi: "Tour và Nếm Bia" },
  { id: 134, en: "Coffee & Tea Tours", vi: "Tour và Nếm Cà Phê & Trà" },
  { id: 135, en: "Cultural Events", vi: "Sự Kiện Văn Hóa" },
  { id: 136, en: "Distillery Tours", vi: "Tour Nhà Pha Chế Rượu" },
  { id: 137, en: "Fashion Shows & Tours", vi: "Tour và Buổi Trình Diễn Thời Trang" },
  { id: 138, en: "Food Tours", vi: "Tour Ăn Uống" },
  { id: 139, en: "Wine Bars", vi: "Quán Bar Rượu" },
  { id: 140, en: "Wine Tours & Tastings", vi: "Tour và Nếm Rượu" },
]

export const transportation_tours = [
  { id: 141, en: "Bus Services", vi: "Dịch Vụ Xe Buýt" },
  { id: 142, en: "Bus Tours", vi: "Tour Xe Buýt" },
  { id: 143, en: "Public Transportation Systems", vi: "Hệ Thống Giao Thông Công Cộng" },
  { id: 144, en: "Rail Services", vi: "Dịch Vụ Đường Sắt" },
  { id: 145, en: "Rail Tours", vi: "Tour Đường Sắt" },
  { id: 146, en: "Scenic Railroads", vi: "Đường Sắt Cảnh Quan" },
  { id: 147, en: "Trams", vi: "Xe Điện" },
]

export const seasons = [
  { id: 1, en: "Spring", vi: "Mùa xuân" },
  { id: 2, en: "Summer", vi: "Mùa hạ" },
  { id: 3, en: "Autumn", vi: "Mùa thu" },
  { id: 4, en: "Winter", vi: "Mùa đông" },
]
