export default [
  {
    label: "Thành phố Bà Rịa",
    label_en: "Bà Rịa City",
    value: 0,
    name: "Ba Ria",
  },
  {
    label: "Thành phố Bạc Liêu",
    label_en: "Bạc Liêu City",
    value: 1,
    name: "Bac Lieu",
  },
  {
    label: "Thành phố Bảo Lộc",
    label_en: "Bảo Lộc City",
    value: 2,
    name: "Bao Loc",
  },
  {
    label: "Thành phố Bắc Giang",
    label_en: "Bắc Giang City",
    value: 3,
    name: "Bac Giang",
  },
  {
    label: "Thành Phố Bắc Kạn",
    label_en: "Bắc Kạn City",
    value: 4,
    name: "Bac Kan",
  },
  {
    label: "Thành phố Bắc Ninh",
    label_en: "Bắc Ninh City",
    value: 5,
    name: "Bac Ninh",
  },
  {
    label: "Thành phố Bến Tre",
    label_en: "Bến Tre City",
    value: 6,
    name: "Ben Tre",
  },
  {
    label: "Thành phố Biên Hòa",
    label_en: "Biên Hòa City",
    value: 7,
    name: "Bien Hoa",
  },
  {
    label: "Thành phố Buôn Ma Thuột",
    label_en: "Buôn Ma Thuột City",
    value: 8,
    name: "Buon Ma Thuot",
  },
  {
    label: "Thành phố Cà Mau",
    label_en: "Cà Mau City",
    value: 9,
    name: "Ca Mau",
  },
  {
    label: "Thành phố Cam Ranh",
    label_en: "Cam Ranh City",
    value: 10,
    name: "Cam Ranh",
  },
  {
    label: "Thành phố Cao Bằng",
    label_en: "Cao Bằng City",
    value: 11,
    name: "Cao Bang",
  },
  {
    label: "Thành phố Cao Lãnh",
    label_en: "Cao Lãnh City",
    value: 12,
    name: "Cao Lanh",
  },
  {
    label: "Thành phố Cẩm Phả",
    label_en: "Cẩm Phả City",
    value: 13,
    name: "Cam Pha",
  },
  {
    label: "Thành phố Cần Thơ",
    label_en: "Cần Thơ City",
    value: 14,
    name: "Can Tho",
  },
  {
    label: "Thành phố Châu Đốc",
    label_en: "Châu Đốc City",
    value: 15,
    name: "Chau Doc",
  },
  {
    label: "Thành phố Chí Linh",
    label_en: "Chí Linh City",
    value: 16,
    name: "Chi Linh",
  },
  {
    label: "Thành phố Dĩ An",
    label_en: "Dĩ An City",
    value: 17,
    name: "Di An",
  },
  {
    label: "Thành phố Đà Lạt",
    label_en: "Đà Lạt City",
    value: 18,
    name: "Da Lat",
  },
  {
    label: "Thành phố Đà Nẵng",
    label_en: "Đà Nẵng City",
    value: 19,
    name: "Da Nang",
  },
  {
    label: "Thành phố Điện Biên Phủ",
    label_en: "Điện Biên Phủ City",
    value: 20,
    name: "Dien Bien Phu",
  },
  {
    label: "Thành phố Đông Hà",
    label_en: "Đông Hà City",
    value: 21,
    name: "Dong Ha",
  },
  {
    label: "Thành Phố Đồng Hới",
    label_en: "Đồng Hới City",
    value: 22,
    name: "Dong Hoi",
  },
  {
    label: "Thành phố Đồng Xoài",
    label_en: "Đồng Xoài City",
    value: 23,
    name: "Dong Xoai",
  },
  {
    label: "Thành phố Gia Nghĩa",
    label_en: "Gia Nghĩa City",
    value: 24,
    name: "Gia Nghia",
  },
  {
    label: "Thành phố Hà Giang",
    label_en: "Hà Giang City",
    value: 25,
    name: "Ha Giang",
  },
  {
    label: "Thành phố Hạ Long",
    label_en: "Hạ Long City",
    value: 26,
    name: "Ha Long",
  },
  {
    label: "Thành phố Hà Nội",
    label_en: "Hà Nội City",
    value: 27,
    name: "Ha Noi",
  },
  {
    label: "Thành phố Hà Tiên",
    label_en: "Hà Tiên City",
    value: 28,
    name: "Ha Tien",
  },
  {
    label: "Thành phố Hà Tĩnh",
    label_en: "Hà Tĩnh City",
    value: 29,
    name: "Ha Tinh",
  },
  {
    label: "Thành phố Hải Dương",
    label_en: "Hải Dương City",
    value: 30,
    name: "Hai Duong",
  },
  {
    label: "Thành phố Hải Phòng",
    label_en: "Hải Phòng City",
    value: 31,
    name: "Hai Phong",
  },
  {
    label: "Thành phố Hòa Bình",
    label_en: "Hòa Bình City",
    value: 32,
    name: "Hoa Binh",
  },
  {
    label: "Thành phố Hồ Chí Minh",
    label_en: "Ho Chi Minh City",
    value: 33,
    name: "Ho Chi Minh",
  },
  {
    label: "Thành phố Hội An",
    label_en: "Hội An City",
    value: 34,
    name: "Hoi An",
  },
  {
    label: "Thành phố Hồng Ngự",
    label_en: "Hồng Ngự City",
    value: 35,
    name: "Hong Ngu",
  },
  {
    label: "Thành phố Huế",
    label_en: "Huế City",
    value: 36,
    name: "Hue",
  },
  {
    label: "Thành phố Hưng Yên",
    label_en: "Hưng Yên City",
    value: 37,
    name: "Hung Yen",
  },
  {
    label: "Thành phố Kon Tum",
    label_en: "Kon Tum City",
    value: 38,
    name: "Kon Tum",
  },
  {
    label: "Thành phố Lai Châu",
    label_en: "Lai Châu City",
    value: 39,
    name: "Lai Chau",
  },
  {
    label: "Thành phố Lạng Sơn",
    label_en: "Lạng Sơn City",
    value: 40,
    name: "Lang Son",
  },
  {
    label: "Thành phố Lào Cai",
    label_en: "Lào Cai City",
    value: 41,
    name: "Lao Cai",
  },
  {
    label: "Thành phố Long Khánh",
    label_en: "Long Khánh City",
    value: 42,
    name: "Long Khanh",
  },
  {
    label: "Thành phố Long Xuyên",
    label_en: "Long Xuyên City",
    value: 43,
    name: "Long Xuyen",
  },
  {
    label: "Thành phố Móng Cái",
    label_en: "Móng Cái City",
    value: 44,
    name: "Mong Cai",
  },
  {
    label: "Thành phố Mỹ Tho",
    label_en: "Mỹ Tho City",
    value: 45,
    name: "My Tho",
  },
  {
    label: "Thành phố Nam Định",
    label_en: "Nam Định City",
    value: 46,
    name: "Nam Dinh",
  },
  {
    label: "Thành phố Ngã Bảy",
    label_en: "Ngã Bảy City",
    value: 47,
    name: "Nga Bay",
  },
  {
    label: "Thành phố Nha Trang",
    label_en: "Nha Trang City",
    value: 48,
    name: "Nha Trang",
  },
  {
    label: "Thành phố Ninh Bình",
    label_en: "Ninh Bình City",
    value: 49,
    name: "Ninh Binh",
  },
  {
    label: "Thành phố Phan Rang-Tháp Chàm",
    label_en: "Phan Rang-Tháp Chàm City",
    value: 50,
    name: "Phan Rang-Thap Cham",
  },
  {
    label: "Thành phố Phan Thiết",
    label_en: "Phan Thiết City",
    value: 51,
    name: "Phan Thiet",
  },
  {
    label: "Thành phố Phủ Lý",
    label_en: "Phủ Lý City",
    value: 52,
    name: "Phu Ly",
  },
  {
    label: "Thành phố Phú Quốc",
    label_en: "Phú Quốc City",
    value: 53,
    name: "Phu Quoc",
  },
  {
    label: "Thành phố Phúc Yên",
    label_en: "Phúc Yên City",
    value: 54,
    name: "Phuc Yen",
  },
  {
    label: "Thành phố Pleiku",
    label_en: "Pleiku City",
    value: 55,
    name: "Pleiku",
  },
  {
    label: "Thành phố Quảng Ngãi",
    label_en: "Quảng Ngãi City",
    value: 56,
    name: "Quang Ngai",
  },
  {
    label: "Thành phố Quy Nhơn",
    label_en: "Quy Nhơn City",
    value: 57,
    name: "Quy Nhon",
  },
  {
    label: "Thành phố Rạch Giá",
    label_en: "Rạch Giá City",
    value: 58,
    name: "Rach Gia",
  },
  {
    label: "Thành phố Sa Đéc",
    label_en: "Sa Đéc City",
    value: 59,
    name: "Sa Dec",
  },
  {
    label: "Thành phố Sầm Sơn",
    label_en: "Sầm Sơn City",
    value: 60,
    name: "Sam Son",
  },
  {
    label: "Thành phố Sóc Trăng",
    label_en: "Sóc Trăng City",
    value: 61,
    name: "Soc Trang",
  },
  {
    label: "Thành phố Sông Công",
    label_en: "Sông Công City",
    value: 62,
    name: "Song Cong",
  },
  {
    label: "Thành phố Sơn La",
    label_en: "Sơn La City",
    value: 63,
    name: "Son La",
  },
  {
    label: "Thành phố Tam Điệp",
    label_en: "Tam Điệp City",
    value: 64,
    name: "Tam Diep",
  },
  {
    label: "Thành phố Tam Kỳ",
    label_en: "Tam Kỳ City",
    value: 65,
    name: "Tam Ky",
  },
  {
    label: "Thành phố Tân An",
    label_en: "Tân An City",
    value: 66,
    name: "Tan An",
  },
  {
    label: "Thành phố Tây Ninh",
    label_en: "Tây Ninh City",
    value: 67,
    name: "Tay Ninh",
  },
  {
    label: "Thành phố Thái Bình",
    label_en: "Thái Bình City",
    value: 68,
    name: "Thai Binh",
  },
  {
    label: "Thành phố Thái Nguyên",
    label_en: "Thái Nguyên City",
    value: 69,
    name: "Thai Nguyen",
  },
  {
    label: "Thành phố Thanh Hóa",
    label_en: "Thanh Hóa City",
    value: 70,
    name: "Thanh Hoa",
  },
  {
    label: "Thành phố Thủ Dầu Một",
    label_en: "Thủ Dầu Một City",
    value: 71,
    name: "Thu Dau Mot",
  },
  {
    label: "Thành phố Thủ Đức",
    label_en: "Thủ Đức City",
    value: 72,
    name: "Thu Duc",
  },
  {
    label: "Thành phố Thuận An",
    label_en: "Thuận An City",
    value: 73,
    name: "Thuan An",
  },
  {
    label: "Thành phố Trà Vinh",
    label_en: "Trà Vinh City",
    value: 74,
    name: "Tra Vinh",
  },
  {
    label: "Thành phố Tuy Hoà",
    label_en: "Tuy Hoà City",
    value: 75,
    name: "Tuy Hoa",
  },
  {
    label: "Thành phố Tuyên Quang",
    label_en: "Tuyên Quang City",
    value: 76,
    name: "Tuyen Quang",
  },
  {
    label: "Thành phố Uông Bí",
    label_en: "Uông Bí City",
    value: 77,
    name: "Uong Bi",
  },
  {
    label: "Thành phố Vị Thanh",
    label_en: "Vị Thanh City",
    value: 78,
    name: "Vi Thanh",
  },
  {
    label: "Thành phố Việt Trì",
    label_en: "Việt Trì City",
    value: 79,
    name: "Viet Tri",
  },
  {
    label: "Thành phố Vinh",
    label_en: "Vinh City",
    value: 80,
    name: "Vinh",
  },
  {
    label: "Thành phố Vĩnh Long",
    label_en: "Vĩnh Long City",
    value: 81,
    name: "Vinh Long",
  },
  {
    label: "Thành phố Vĩnh Yên",
    label_en: "Vĩnh Yên City",
    value: 82,
    name: "Vinh Yen",
  },
  {
    label: "Thành phố Vũng Tàu",
    label_en: "Vũng Tàu City",
    value: 83,
    name: "Vung Tau",
  },
  {
    label: "Thành phố Yên Bái",
    label_en: "Yên Bái City",
    value: 84,
    name: "Yen Bai",
  },
  {
    label: "Tỉnh An Giang",
    label_en: "An Giang Province",
    value: 85,
    name: "An Giang",
  },
  {
    label: "Tỉnh Bà Rịa - Vũng Tàu",
    label_en: "Bà Rịa - Vũng Tàu Province",
    value: 86,
    name: "Ba Ria - Vung Tau",
  },
  {
    label: "Tỉnh Bạc Liêu",
    label_en: "Bạc Liêu Province",
    value: 87,
    name: "Bac Lieu",
  },
  {
    label: "Tỉnh Bắc Giang",
    label_en: "Bắc Giang Province",
    value: 88,
    name: "Bac Giang",
  },
  {
    label: "Tỉnh Bắc Kạn",
    label_en: "Bắc Kạn Province",
    value: 89,
    name: "Bac Kan",
  },
  {
    label: "Tỉnh Bắc Ninh",
    label_en: "Bắc Ninh Province",
    value: 90,
    name: "Bac Ninh",
  },
  {
    label: "Tỉnh Bến Tre",
    label_en: "Bến Tre Province",
    value: 91,
    name: "Ben Tre",
  },
  {
    label: "Tỉnh Bình Dương",
    label_en: "Bình Dương Province",
    value: 92,
    name: "Binh Duong",
  },
  {
    label: "Tỉnh Bình Định",
    label_en: "Bình Định Province",
    value: 93,
    name: "Binh Dinh",
  },
  {
    label: "Tỉnh Bình Phước",
    label_en: "Bình Phước Province",
    value: 94,
    name: "Binh Phuoc",
  },
  {
    label: "Tỉnh Bình Thuận",
    label_en: "Bình Thuận Province",
    value: 95,
    name: "Binh Thuan",
  },
  {
    label: "Tỉnh Cà Mau",
    label_en: "Cà Mau Province",
    value: 96,
    name: "Ca Mau",
  },
  {
    label: "Tỉnh Cao Bằng",
    label_en: "Cao Bằng Province",
    value: 97,
    name: "Cao Bang",
  },
  {
    label: "Tỉnh Đắk Lắk",
    label_en: "Đắk Lắk Province",
    value: 98,
    name: "Dak Lak",
  },
  {
    label: "Tỉnh Đắk Nông",
    label_en: "Đắk Nông Province",
    value: 99,
    name: "Dak Nong",
  },
  {
    label: "Tỉnh Điện Biên",
    label_en: "Điện Biên Province",
    value: 100,
    name: "Dien Bien",
  },
  {
    label: "Tỉnh Đồng Nai",
    label_en: "Đồng Nai Province",
    value: 101,
    name: "Dong Nai",
  },
  {
    label: "Tỉnh Đồng Tháp",
    label_en: "Đồng Tháp Province",
    value: 102,
    name: "Dong Thap",
  },
  {
    label: "Tỉnh Gia Lai",
    label_en: "Gia Lai Province",
    value: 103,
    name: "Gia Lai",
  },
  {
    label: "Tỉnh Hà Giang",
    label_en: "Hà Giang Province",
    value: 104,
    name: "Ha Giang",
  },
  {
    label: "Tỉnh Hà Nam",
    label_en: "Hà Nam Province",
    value: 105,
    name: "Ha Nam",
  },
  {
    label: "Tỉnh Hà Tĩnh",
    label_en: "Hà Tĩnh Province",
    value: 106,
    name: "Ha Tinh",
  },
  {
    label: "Tỉnh Hải Dương",
    label_en: "Hải Dương Province",
    value: 107,
    name: "Hai Duong",
  },
  {
    label: "Tỉnh Hậu Giang",
    label_en: "Hậu Giang Province",
    value: 108,
    name: "Hau Giang",
  },
  {
    label: "Tỉnh Hoà Bình",
    label_en: "Hoà Bình Province",
    value: 109,
    name: "Hoa Binh",
  },
  {
    label: "Tỉnh Hưng Yên",
    label_en: "Hưng Yên Province",
    value: 110,
    name: "Hung Yen",
  },
  {
    label: "Tỉnh Khánh Hòa",
    label_en: "Khánh Hòa Province",
    value: 111,
    name: "Khanh Hoa",
  },
  {
    label: "Tỉnh Kiên Giang",
    label_en: "Kiên Giang Province",
    value: 112,
    name: "Kien Giang",
  },
  {
    label: "Tỉnh Kon Tum",
    label_en: "Kon Tum Province",
    value: 113,
    name: "Kon Tum",
  },
  {
    label: "Tỉnh Lai Châu",
    label_en: "Lai Châu Province",
    value: 114,
    name: "Lai Chau",
  },
  {
    label: "Tỉnh Lạng Sơn",
    label_en: "Lạng Sơn Province",
    value: 115,
    name: "Lang Son",
  },
  {
    label: "Tỉnh Lào Cai",
    label_en: "Lào Cai Province",
    value: 116,
    name: "Lao Cai",
  },
  {
    label: "Tỉnh Lâm Đồng",
    label_en: "Lâm Đồng Province",
    value: 117,
    name: "Lam Dong",
  },
  {
    label: "Tỉnh Long An",
    label_en: "Long An Province",
    value: 118,
    name: "Long An",
  },
  {
    label: "Tỉnh Nam Định",
    label_en: "Nam Định Province",
    value: 119,
    name: "Nam Dinh",
  },
  {
    label: "Tỉnh Nghệ An",
    label_en: "Nghệ An Province",
    value: 120,
    name: "Nghe An",
  },
  {
    label: "Tỉnh Ninh Bình",
    label_en: "Ninh Bình Province",
    value: 121,
    name: "Ninh Binh",
  },
  {
    label: "Tỉnh Ninh Thuận",
    label_en: "Ninh Thuận Province",
    value: 122,
    name: "Ninh Thuan",
  },
  {
    label: "Tỉnh Phú Thọ",
    label_en: "Phú Thọ Province",
    value: 123,
    name: "Phu Tho",
  },
  {
    label: "Tỉnh Phú Yên",
    label_en: "Phú Yên Province",
    value: 124,
    name: "Phu Yen",
  },
  {
    label: "Tỉnh Quảng Bình",
    label_en: "Quảng Bình Province",
    value: 125,
    name: "Quang Binh",
  },
  {
    label: "Tỉnh Quảng Nam",
    label_en: "Quảng Nam Province",
    value: 126,
    name: "Quang Nam",
  },
  {
    label: "Tỉnh Quảng Ngãi",
    label_en: "Quảng Ngãi Province",
    value: 127,
    name: "Quang Ngai",
  },
  {
    label: "Tỉnh Quảng Ninh",
    label_en: "Quảng Ninh Province",
    value: 128,
    name: "Quang Ninh",
  },
  {
    label: "Tỉnh Quảng Trị",
    label_en: "Quảng Trị Province",
    value: 129,
    name: "Quang Tri",
  },
  {
    label: "Tỉnh Sóc Trăng",
    label_en: "Sóc Trăng Province",
    value: 130,
    name: "Soc Trang",
  },
  {
    label: "Tỉnh Sơn La",
    label_en: "Sơn La Province",
    value: 131,
    name: "Son La",
  },
  {
    label: "Tỉnh Tây Ninh",
    label_en: "Tây Ninh Province",
    value: 132,
    name: "Tay Ninh",
  },
  {
    label: "Tỉnh Thái Bình",
    label_en: "Thái Bình Province",
    value: 133,
    name: "Thai Binh",
  },
  {
    label: "Tỉnh Thái Nguyên",
    label_en: "Thái Nguyên Province",
    value: 134,
    name: "Thai Nguyen",
  },
  {
    label: "Tỉnh Thanh Hóa",
    label_en: "Thanh Hóa Province",
    value: 135,
    name: "Thanh Hoa",
  },
  {
    label: "Tỉnh Thừa Thiên Huế",
    label_en: "Thừa Thiên Huế Province",
    value: 136,
    name: "Thua Thien Hue",
  },
  {
    label: "Tỉnh Tiền Giang",
    label_en: "Tiền Giang Province",
    value: 137,
    name: "Tien Giang",
  },
  {
    label: "Tỉnh Trà Vinh",
    label_en: "Trà Vinh Province",
    value: 138,
    name: "Tra Vinh",
  },
  {
    label: "Tỉnh Tuyên Quang",
    label_en: "Tuyên Quang Province",
    value: 139,
    name: "Tuyen Quang",
  },
  {
    label: "Tỉnh Vĩnh Long",
    label_en: "Vĩnh Long Province",
    value: 140,
    name: "Vinh Long",
  },
  {
    label: "Tỉnh Vĩnh Phúc",
    label_en: "Vĩnh Phúc Province",
    value: 141,
    name: "Vinh Phuc",
  },
  {
    label: "Tỉnh Yên Bái",
    label_en: "Yên Bái Province",
    value: 142,
    name: "Yen Bai",
  },
]
